/**
 * API Route: Get Madani Mushaf page numbers for a surah
 * Reads from the pre-built public/quran-page-numbers.json (generated by scripts/fetch-page-numbers.ts)
 * Returns: { success: true, data: { [ayah: number]: pageNumber } }
 */

import { NextRequest, NextResponse } from "next/server";
import { readFileSync } from "fs";
import { resolve } from "path";

// Load once at module level — stays in memory for the lifetime of the process
let pageData: Record<string, Record<string, number>> | null = null;

function getPageData() {
  if (!pageData) {
    const filePath = resolve(process.cwd(), "public", "quran-page-numbers.json");
    pageData = JSON.parse(readFileSync(filePath, "utf-8"));
  }
  return pageData!;
}

export async function GET(
  _request: NextRequest,
  { params }: { params: Promise<{ surah: string }> }
) {
  const { surah } = await params;
  const surahNum = parseInt(surah, 10);

  if (isNaN(surahNum) || surahNum < 1 || surahNum > 114) {
    return NextResponse.json(
      { success: false, error: "Invalid surah number" },
      { status: 400 }
    );
  }

  try {
    const data = getPageData();
    const surahMap = data[String(surahNum)];

    if (!surahMap) {
      return NextResponse.json(
        { success: false, error: `No page data for surah ${surahNum}` },
        { status: 404 }
      );
    }

    // Convert string keys to numbers for the client
    const result: Record<number, number> = {};
    for (const [ayah, page] of Object.entries(surahMap)) {
      result[Number(ayah)] = page;
    }

    return NextResponse.json({ success: true, data: result });
  } catch (err) {
    console.error("[page-info] Error:", err);
    return NextResponse.json(
      { success: false, error: "Failed to read page data" },
      { status: 500 }
    );
  }
}
